ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'DONO';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'FUNCIONARIO';

UPDATE usuario
SET role = 'FUNCIONARIO'
WHERE role IN ('BARBEIRO', 'GERENTE', 'RECEPCIONISTA');
